"""nutrition: foods and meal_logs

Revision ID: cb049c0b12d1
Revises: a872e54fc5fc
Create Date: 2026-06-03 17:09:44.767662
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'cb049c0b12d1'
down_revision = 'a872e54fc5fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('serving_size', sa.String(), nullable=True),
    sa.Column('calories', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('fiber_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sugar_g', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=False)
    op.create_index(op.f('ix_foods_user_id'), 'foods', ['user_id'], unique=False)
    op.create_table('meal_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.String(), nullable=False),
    sa.Column('servings', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('logged_on', sa.Date(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_logs_logged_on'), 'meal_logs', ['logged_on'], unique=False)
    op.create_index(op.f('ix_meal_logs_user_id'), 'meal_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_logs_user_id'), table_name='meal_logs')
    op.drop_index(op.f('ix_meal_logs_logged_on'), table_name='meal_logs')
    op.drop_table('meal_logs')
    op.drop_index(op.f('ix_foods_user_id'), table_name='foods')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
